import { registerUser } from "../../controllers/authController";
import { NextRequest, NextResponse } from "next/server";
import { Account } from "../../middlewares/schemas";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json(); // Get the body from the request
    const validationResult = Account.safeParse(body);

    if (!validationResult.success) {
      return NextResponse.json(
        { error: "Validation failed", details: validationResult.error.issues },
        { status: 400 }
      );
    }

    // Call the controller logic to register the user
    const { name, email, password, username } = validationResult.data;
    const response = await registerUser(name, email, password, username);

    return response; // Return the response generated by the controller
  } catch (err) {
    console.error("Error during registration:", err);
    return NextResponse.json(
      { error: "Internal Server Error", details: err },
      { status: 500 }
    );
  }
}
